### ISSUE TITLE
Necesito buscar patente

### ISSUE THREAD

**Issue by richard474** [Xpertians/odc#73]

**Comment by oscarvalenzuelab** [comment]
Hola Richard,

Probaste con http://www.multidata.cl?

**Comment by richard474** [comment]
Hola no supe como hacerlo¡¡¡

rt

 

De: Oscar Valenzuela <notifications@github.com> 
Enviado el: miércoles, 29 de mayo de 2019 15:50
Para: Xpertians/odc <odc@noreply.github.com>
CC: richard474 <rtapia@prodalysa.cl>; Author <author@noreply.github.com>
Asunto: Re: [Xpertians/odc] Necesito buscar patente (#73)

 

Hola Richard,

Probaste con http://www.multidata.cl?
