### ISSUE TITLE
Suport

### ISSUE THREAD

**Issue by chrizbosty** [Xpertians/odc#74]
Dear I am trying to access your service and I get only the "Access Denied" message

Could you guide me in what am I doing wrong?

Background:

- I use the sample codes of your CURL from the site: (https://odc.xpertians.com/)
- I have 1500 credits in the account
- I have an active client, in which the URL corresponds to my development (in case the consultations are limited to a certain URL)
- I get a valid token in the first Curl.
- I use the driver corresponding to the car api.
- I have tried with several different patents.

* I attach images of my code, and a php file with it.
![Codigo 1](https://user-images.githubusercontent.com/55596730/67020498-af856a00-f0d4-11e9-9b49-88c799a87569.png)
![Codigo 2](https://user-images.githubusercontent.com/55596730/67020499-af856a00-f0d4-11e9-9a37-624c45904520.png)

**Comment by oscarvalenzuelab** [comment]
Hi chrizbosty, hey did you assigned the client to the specific controller you are querying?

1. Please go to the catalog, then open the specific controller you are using.
2. Click the button at the bottom to "request access", it could be in spanish "solicitar acceso".
3. Select your client, and add it to the controller.

Please confirm if that is working. Also, please note the access_token you displayed there is too short, a normal token should be way way longer.

thanks,
Oscar.

**Comment by oscarvalenzuelab** [comment]
No response for 14 days. Resolving for now, please feel free to reopen the ticket.
