### ISSUE TITLE
Problems connecting with Postman

### ISSUE THREAD

**Issue by cmodinger** [Xpertians/odc#75]
Estimado Oscar, por esas cosas de la vida estoy trabajando Gino Cabrera en un proyecto y me quiería conectar a la API de multiservicios acá en Chile.

Hice algunos intentos creandome una cuenta de cliente y con las IDs.

Leyendo los ejemplo que están publicados tampoco me resulto, me podrías enviar un Postman operando al menos en el flujo de consulta de vehiculos o patentes.

Saludos y gracias

**Comment by oscarvalenzuelab** [comment]
Hola!

Excelente, mira intenta con este ejemplo:
https://odc.xpertians.com/docs/ejemplos-de-implementacion/#usando-postman

Si no funciona, entonces avisame y hacemos una video conferencia.
Por cierto, es el ticket linkeado abajo tuyo?
https://github.com/Xpertians/odc/issues/74

Saludos,
Oscar

**Comment by cmodinger** [comment]
Hola Osacar, sabes que solo llegue hasta el segundo paso.

Solicitar el token ningún problema funciona perfecto pero cuando trato de recuperar el dato me da accesos denegado y ya compré 1.000 créditos para hacer las pruebas antes para asegurarme que estaba todo ok.

¿Qué crees que pueda ser? 






Gracias mil

**Comment by oscarvalenzuelab** [comment]
Pero asignaste el cliente al collector que quieres usar?
Insisto, yo creo que el problema esta en que el cliente no tiene permisos para consultar el collector.

Abre el detalle del colector que quieres consultar, abajo tiene un boton que dice solicitar acceso. Ahi seleccionas el cliente que creaste y luego lo asignas.

**Comment by oscarvalenzuelab** [comment]
Confirmado que el problema de conexion fue solucionado.
