### ISSUE TITLE
Error  al hacer las consultas.

### ISSUE THREAD

**Issue by cmodinger** [Xpertians/odc#76]
Cuando renuevo el token y solcito alguna información, todos los data collector me bloquean el acceso. He leido todo pero no logré encontrara ninguna referencia para poder continuar.

Saludos y gracias.

<img width="981" alt="Captura de Pantalla 2019-11-01 a la(s) 07 20 34" src="https://user-images.githubusercontent.com/19255305/68062316-75c57d80-fce8-11e9-923c-eebc1db24181.png">

**Comment by oscarvalenzuelab** [comment]
Resolviendo como dupe de https://github.com/Xpertians/odc/issues/75
