### ISSUE TITLE
Objeto dentro de objeto

### ISSUE THREAD

**Issue by cmodinger** [Xpertians/odc#77]
Estimado Oscar, espero estes muy bien.

Con la información que nos entregaste ya logramos comunicación exitosa por medio de Postman.

El problema que nos surge ahora es que al tratar de parsear el JSON. Vimos que existe un número tipo objeto dinámico el cual nos imposibilita poder asignar variables.

La idea sería poder sacar esa linea del servicio y ya podríamos poder operar.

Te adjunto imagen de la linea que sería bueno eliminar para  poder hacer el parseo con facilidad.
<img width="540" alt="Captura de Pantalla 2019-11-04 a la(s) 21 36 16" src="https://user-images.githubusercontent.com/19255305/68220044-c1687780-ffc5-11e9-92d8-614f5a8c322d.png">

**Comment by oscarvalenzuelab** [comment]
Hola Christian,

Converse con Gino offline respecto a este problema.
Lamentablemente no puedo hacer cambios al output, ya que hay otros clientes haciendo uso de la plataforma y consumen la misma data. El objeto se genera dinamicamente dado que existen diferentes tipos de estructuras y versiones, y aunque puedes filtrar usando un lenguaje de programacion, la mejor forma para tu caso es usar la nueva plataforma.

Te contacto offline (email) para entregarte las credenciales.

Saludos,
Oscar.
