### ISSUE TITLE
Excesos Fonasa

### ISSUE THREAD

**Issue by oscarvalenzuelab** [Xpertians/odc#94]
https://twitter.com/FONASA/status/1180084317877350400

Requiere investigacion. No se puede acceder desde fuera de CL y no es claro que dato entrega.
Idealmente sera asignado a Andres para ser investigado

**Comment by asotomayorx** [comment]
Estimados usuarios

Comunicamos que el proceso masivo de devolución de cotizaciones pagadas en exceso(DPE) ha finalizado.

https://www.fonasa.cl/sites/fonasa/mobile/beneficiarios/servicios/interior?servicio=cont-devolucion

**Comment by oscarvalenzuelab** [comment]
Eso significa que ya no está disponible?

**Comment by asotomayorx** [comment]
Exacto, todos las páginas que hablan del tema llevan a un enlace que ya no existe;

https://www.latercera.com/noticia/excesos-fonasa-como/
